### PR TITLE
Update default scan interval to 5 minutes to avoid quota limits

### PR DESCRIPTION
**Pull request by epenet**

### CODE REVIEW

**Comment by epenet** [comment]
Fix #68

**Review by oncleben31 — APPROVED** [review]

**Comment by gajotnt** [comment]
Hello using Home Assistant Renault integration.
Having a issue thats probably related to this, during 15min the sensors become **unavailable**
Below an image of the sensor history, and some logs.

renault


```
Logger: homeassistant.components.renault.renault_vehicle
Source: helpers/update_coordinator.py:223
Integration: Renault (documentation, issues)
First occurred: June 7, 2022, 8:48:04 PM (115 occurrences)
Last logged: 10:44:49 AM

Error fetching XXXXXXXXXXXXXXXX charge_mode data: Error communicating with API: ('err.func.wired.unauthorized', 'The access is unauthorized')
Error fetching XXXXXXXXXXXXXXXX cockpit data: Error communicating with API: ('err.func.wired.unauthorized', 'The access is unauthorized')
Error fetching XXXXXXXXXXXXXXXX battery data: Error communicating with API: ('err.func.wired.unauthorized', 'The access is unauthorized')
Error fetching XXXXXXXXXXXXXXXX hvac_status data: Error communicating with API: ('err.func.wired.unauthorized', 'The access is unauthorized')
```

```
Logger: homeassistant.components.renault.renault_vehicle
Source: helpers/update_coordinator.py:204
Integration: Renault (documentation, issues)
First occurred: 9:38:18 AM (4 occurrences)
Last logged: 9:38:19 AM

Error requesting XXXXXXXXXXXXXXXX cockpit data: 502, message='Bad Gateway', url=URL('https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/5648bc36-f779-40d8-9f4e-458d618dc514/kamereon/kca/car-adapter/v2/cars/XXXXXXXXXXXXXXXX/cockpit?country=PT')
Error requesting XXXXXXXXXXXXXXXX charge_mode data: 502, message='Bad Gateway', url=URL('https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/5648bc36-f779-40d8-9f4e-458d618dc514/kamereon/kca/car-adapter/v1/cars/XXXXXXXXXXXXXXXX/charge-mode?country=PT')
Error requesting XXXXXXXXXXXXXXXX hvac_status data: 502, message='Bad Gateway', url=URL('https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/5648bc36-f779-40d8-9f4e-458d618dc514/kamereon/kca/car-adapter/v1/cars/XXXXXXXXXXXXXXXX/hvac-status?country=PT')
Error requesting XXXXXXXXXXXXXXXX battery data: 502, message='Bad Gateway', url=URL('https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/5648bc36-f779-40d8-9f4e-458d618dc514/kamereon/kca/car-adapter/v2/cars/XXXXXXXXXXXXXXXX/battery-status?country=PT')
```



```
{
  "home_assistant": {
    "installation_type": "Home Assistant Core",
    "version": "2022.6.1",
    "dev": false,
    "hassio": false,
    "virtualenv": true,
    "python_version": "3.9.9",
    "docker": false,
    "arch": "amd64",
    "timezone": "Atlantic/Azores",
    "os_name": "FreeBSD",
    "os_version": "12.2-RELEASE-p11",
    "run_as_root": false
  },
  "custom_components": {
    "hacs": {
      "version": "1.25.5",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "reolink_dev": {
      "version": "0.54",
      "requirements": [
        "reolink==0.0.61"
      ]
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "sql_json": {
      "version": "1.1.2",
      "requirements": [
        "sqlalchemy~=1.4.27"
      ]
    }
  },
  "integration_manifest": {
    "domain": "renault",
    "name": "Renault",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/renault",
    "requirements": [
      "renault-api==0.1.11"
    ],
    "codeowners": [
      "@epenet"
    ],
    "iot_class": "cloud_polling",
    "loggers": [
      "renault_api"
    ],
    "supported_brands": {
      "dacia": "Dacia"
    },
    "is_built_in": true
  },
  "data": {
    "entry": {
      "title": "Zoe",
      "data": {
        "locale": "pt_PT",
        "username": "**REDACTED**",
        "password": "**REDACTED**",
        "gigya-root-url": "https://accounts.eu1.gigya.com",
        "gigya-api-key": "3__afxovspi2-Ip1E5kNsAgc4_35lpLAKCF6bq4_xXj2I2bFPjIWxAOAQJlIkreKTD",
        "kamereon-root-url": "https://api-wired-prod-1-euw1.wrd-aws.com",
        "kamereon-api-key": "VAX7XYKGfa92yMvXculCkEFyfZbuM7Ss",
        "kamereon_account_id": "**REDACTED**"
      }
    },
    "vehicles": [
      {
        "details": {
          "vin": "**REDACTED**",
          "registrationDate": "2018-11-19",
          "firstRegistrationDate": "2018-11-19",
          "engineType": "5AQ",
          "engineRatio": "607",
          "modelSCR": "ZOE",
          "deliveryCountry": {
            "code": "PT",
            "label": "PORTUGAL"
          },
          "family": {
            "code": "X10",
            "label": "",
            "group": "007"
          },
          "tcu": {
            "code": "TCU0G2",
            "label": "TCU VER 0 GEN 2",
            "group": "E70"
          },
          "navigationAssistanceLevel": {
            "code": "NAV3G5",
            "label": "NAVIGATION AID 5 LEVEL 3",
            "group": "408"
          },
          "battery": {
            "code": "BT4AR1",
            "label": "BT4AR1 BATTERY",
            "group": "968"
          },
          "radioType": {
            "code": "RAD06D",
            "label": "RADIO 06D",
            "group": "425"
          },
          "registrationCountry": {
            "code": "PT"
          },
          "brand": {
            "label": "RENAULT"
          },
          "model": {
            "code": "X101VE",
            "label": "ZOE",
            "group": "971"
          },
          "gearbox": {
            "code": "BVEL",
            "label": "ELEC.VAR.GEARBOX",
            "group": "427"
          },
          "version": {
            "code": "LTD MF 18RP"
          },
          "energy": {
            "code": "ELEC",
            "label": "ELECTRICITY",
            "group": "019"
          },
          "registrationNumber": "**REDACTED**",
          "vcd": "STANDA/X10/B10/EA2/MF/ELEC/DG/TEMP/TR4X2/RV/ABS/CAREG/LAC/VT003/CPE/RET03/SPROJA/RALU16/CEAVRH/AIRBA1/SERIE/DRA/DRAP08/HARM02/3ATRPH/OV369/SFBANA/KM/DPRPN/AVREPL/SSDECA/ASRESP/RDAR02/ALEVA/CACBL2/SOP02C/CTHAB2/TRNOR/LVAVIP/LVAREL/SASURV/KTGREP/SGSCHA/APL03/ALOUCC/CMAR3P/NAV3G5/RAD06D/BVEL/AUTAUG/RNORM/ISOFIX/EQPEUR/HRGM01/SDPCLV/TLFRAN/SPRODI/SAN613/SSAPEX/GENEV2/ELC1/SANCML/PE2012/PHAS1/LTD/045KWH/BT4AR1/VEC233/X101VE/NBT017/5AQ/SYTINC/SKTPOU/SAND41/FDIU1/SSESM/MAPSTD/SSCALL/SAND88/SAND90/SQKDRO/SDIFPA/FACBA2/PRLEX1/SSRCAR/CABDO2/TCU0G2/SWALBO/EVTEC1/SPMIR/EVCER",
          "assets": [
            {
              "assetType": "PICTURE",
              "renditions": [
                {
                  "resolutionType": "ONE_MYRENAULT_LARGE",
                  "url": "https://3dv.renault.com/ImageFromBookmark?configuration=STANDA%2FB10%2FEA2%2FDG%2FVT003%2FRET03%2FRALU16%2FDRAP08%2FHARM02%2F3ATRPH%2FOV369%2FRDAR02%2FALEVA%2FSOP02C%2FTRNOR%2FLVAVIP%2FLVAREL%2FNAV3G5%2FRAD06D%2FSDPCLV%2FTLFRAN%2FGENEV2%2FLTD%2FBT4AR1%2FNBT017%2FSKTPOU%2FPRLEX1&databaseId=b4572adc-6c81-48ef-b4b1-2aff24ed7550&bookmarkSet=RSITE&bookmark=EXT_34_DESSUS&profile=HELIOS_OWNERSERVICES_LARGE"
                },
                {
                  "resolutionType": "ONE_MYRENAULT_SMALL",
                  "url": "https://3dv.renault.com/ImageFromBookmark?configuration=STANDA%2FB10%2FEA2%2FDG%2FVT003%2FRET03%2FRALU16%2FDRAP08%2FHARM02%2F3ATRPH%2FOV369%2FRDAR02%2FALEVA%2FSOP02C%2FTRNOR%2FLVAVIP%2FLVAREL%2FNAV3G5%2FRAD06D%2FSDPCLV%2FTLFRAN%2FGENEV2%2FLTD%2FBT4AR1%2FNBT017%2FSKTPOU%2FPRLEX1&databaseId=b4572adc-6c81-48ef-b4b1-2aff24ed7550&bookmarkSet=RSITE&bookmark=EXT_34_DESSUS&profile=HELIOS_OWNERSERVICES_SMALL_V2"
                }
              ]
            },
            {
              "assetType": "VIDEO",
              "assetRole": "CAR",
              "title": "video",
              "description": "",
              "renditions": [
                {
                  "url": "AVBtB97yd_c"
                }
              ]
            }
          ],
          "yearsOfMaintenance": 12,
          "connectivityTechnology": "NONE",
          "easyConnectStore": false,
          "electrical": true,
          "rlinkStore": false,
          "deliveryDate": "2018-12-26",
          "retrievedFromDhs": false,
          "engineEnergyType": "ELEC",
          "radioCode": "**REDACTED**"
        },
        "data": {
          "cockpit": {
            "totalMileage": 51626.9
          },
          "hvac_status": {
            "hvacStatus": "off",
            "externalTemperature": 19.0
          },
          "battery": {
            "timestamp": "2022-06-08T12:35:19+02:00",
            "batteryLevel": 59,
            "batteryTemperature": 20,
            "batteryAutonomy": 194,
            "batteryCapacity": 0,
            "batteryAvailableEnergy": 0,
            "plugStatus": 0,
            "chargingStatus": -1.0
          },
          "charge_mode": {
            "chargeMode": "always_charging"
          }
        }
      }
    ]
  }
}
```

**Comment by epenet** [comment]
The Renault integration was originally merged into core in 2021.8 and finalised in 2021.10. The use of this custom component has been deprecated since then and should no longer be used

**Comment by gajotnt** [comment]
Hmm ok thanks

**Pull request merged**
