### PR TITLE
Add option to use kWh instead of Wh

### PR DESCRIPTION
**Pull request by myhrmans**
Some new cars, etc. ZE50 report charging power in kWh instead of Wh like they used to do before. 
Add configuration option to not divide by 1000.

### CODE REVIEW

**Comment by epenet** [comment]
Hi @myhrmans,
I'm working to migrate this into the core of Home Assistant: https://github.com/home-assistant/core/pull/39605

Can we review this once that is merged in?

**Comment by epenet** [comment]
Hi @myhrmans,

Since the home assistant core is likely to take a while to be merged in, I've just pushed a brand new custom_component.

It includes a config_flow, and moves to a new domain (renault instead of renaultze).
Can you rebase your PR, and either use the "model_code" to force kWh for ZE50 (X102VE), or add an option on the config_flow.

Since I only have a ZE40, it's hard for me to test.

**Comment by etobi** [comment]
I can test this, as soon as this PR is updated and conflicts are solved.

**Comment by epenet** [comment]
Do we know if it's a global thing (all ZE50/X102VE use kWh) or a settings that is per-vehicle?
If it's global then easier to setup but don't want to do that work and find I have to implement per-vehicle.

**Comment by myhrmans** [comment]
> Do we know if it's a global thing (all ZE50/X102VE use kWh) or a settings that is per-vehicle?
> If it's global then easier to setup but don't want to do that work and find I have to implement per-vehicle.

All ZE50 report in kWh from what I know. I'll try to fix the PR this weekend if I have time!

**Comment by etobi** [comment]
If its wrong for all ZE50 - maybe this is already wrong and should be fixed in pyze instead?

**Comment by epenet** [comment]
No, it's not a PyZe issue. Pyze API simply returns the data from Renault and doesn't make any amends on it.
It's just a display issue.

I'll take a look at it next week if @myhrmans doesn't get a chance to look at it over the weekend.

**Comment by epenet** [comment]
Can you please try latest from dev branch to see if 56f00ba778bd2f570a41525d4d2863612faa3794 fixes this correctly?

**Comment by etobi** [comment]
> Can you please try latest from dev branch to see if [56f00ba](https://github.com/epenet/hassRenaultZE/commit/56f00ba778bd2f570a41525d4d2863612faa3794) fixes this correctly?

Look good for me.
`sensor.vf1ag[...]_charging_power` now report the same value as `pyze status --kw` does.

(however i think pyze reports a wrong value...)

**Comment by epenet** [comment]
@myhrmans are you happy to close this now?

**Comment by myhrmans** [comment]
> > Can you please try latest from dev branch to see if [56f00ba](https://github.com/epenet/hassRenaultZE/commit/56f00ba778bd2f570a41525d4d2863612faa3794) fixes this correctly?
> 
> Look good for me.
> `sensor.vf1ag[...]_charging_power` now report the same value as `pyze status --kw` does.
> 
> (however i think pyze reports a wrong value...)

Are you talking about the kW not being accurate and completely off? I see that aswell but apparently it's something on renault's end @etobi.
Yes I'll close this. Thanks @epenet!

**Comment by etobi** [comment]
> Are you talking about the kW not being accurate and completely off? I see that aswell but apparently it's something on renault's end @etobi.

Yes. I was about to file an issue in pyze - but while debugging i noticed the renault endpoint seem to report wrong data here.
(Renault reports sth between 14 and 20 - but my wallbox delivers only up to 11kW)

**Comment by myhrmans** [comment]
> > Are you talking about the kW not being accurate and completely off? I see that aswell but apparently it's something on renault's end @etobi.
> 
> Yes. I was about to file an issue in pyze - but while debugging i noticed the renault endpoint seem to report wrong data here.
> (Renault reports sth between 14 and 20 - but my wallbox delivers only up to 11kW)

Yes @etobi. Hopefully this will resolved in future updates for the ZE50

**Pull request closed without merging**
