### PR TITLE
Add GPS Attribute to sensor

### PR DESCRIPTION
**Pull request by myhrmans**

### CODE REVIEW

**Comment by myhrmans** [comment]
Example in lovelace UI to show the car, in this case a Zoe, on the map.

```
type: map
default_zoom: 13
entities:
  - entity: sensor.zoe
hours_to_show: 24
```

**Comment by epenet** [comment]
Hi @myhrmans 

Thanks for the PR, but I think some of this is already available in the [develop branch](https://github.com/epenet/hassRenaultZE/tree/develop).
Can you please review your PR accordingly?

**Comment by epenet** [comment]
Hi,

If you rebase the patch against the develop branch, you'll find that only the Readme update becomes relevant.

**Comment by myhrmans** [comment]
Hi @epenet 
I see. Missed the development branch when I did the commit. 

One note: 
I think the Map Card in Home Assistant needs the attributes without "location_" before lng and lat. 
Not sure about this tho.
I'll remove this PR since it's not relevant anymore.

**Pull request closed without merging**
